### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by PitoneMaledetto** [severindupouy/conky.conf#1]
Hi,
thank you for sharing your configuration file.
How can I add new icons in the conf file in order to display more stats?
I have installed the fonts needed but I can't seem to be able to render any.
Thanks

p.s. I edit my file using vim

**Comment by severindupouy** [comment]
If anybody needs : 
to ask for using fontawesome : 
${font Font Awesome 5 Free:style=Solid:size=10}
after, put the icon.
after, to ask for using back the global font: ${font}

so, it's like this (but the icon can't be displayed correctly in this comment) : 
${font Font Awesome 5 Free:style=Solid:size=10}some_awesome_icon ${font}other_things_to_displayed_with_normal_font
